version: '3.4'

services:
  innoscripta-newsroom:
    image: harshitsangani/innoscripta-newsroom
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000